### ISSUE TITLE
Feature request:  display date in Inbox

### ISSUE THREAD

**Issue by stephanielitus** [OpenFn/docs#100]
The text weekday dates, i.e. "Last Sunday" are difficult to work with.  I find myself opening a calendar to see what date that is when looking for specific items based on date in the Inbox.  I'd prefer to see all the dates in the MM/DD/YYYY format

**Comment by taylordowns2000** [comment]
Hey @stephanielitus , thanks for this suggestion and apologies for the long delay. We've compromised to show "today" and "yesterday" but the full `YYYY-MM-DD` format for all other dates. (This is on both the `Activity History` and `Inbox` page. We've also added a hover feature which will show you the full date and time ago for each record, regardless of when it started/was inserted. Hope this does the trick!
![image](https://user-images.githubusercontent.com/8732845/54082830-2f637e80-4313-11e9-8d8b-7f6401e55e36.png)

Delivered in `v1.22.2`
