### ISSUE TITLE
Cannot run custom function

### ISSUE THREAD

**Issue by paward35** [OpenFn/docs#102]
Hi, I'm having trouble running a custom function. Here's the current state of the code 

<img width="1064" alt="screenshot 2018-11-06 at 21 59 03" src="https://user-images.githubusercontent.com/26251420/48096608-86dfc980-e20f-11e8-9431-451e93342ad8.png">

The console log statements are being executed which makes me think that the code is being run, however, the create statements for the Goal_Items__c are not being executed and the data for the Goal_Items is not being sent to Salesforce. The two upsert statements are executing successfully. I have tried running the function below by including:

createGoalItems();

As the last line of the program but I get an error: 

createGoalItems is not defined.

I would greatly appreciate help with this issue! Thank you for your time.

**Comment by taylordowns2000** [comment]
I know this is ancient, but for posterity: https://docs.openfn.org/core.html#sequences-of-operations-inside-custom-functions

Check out the above docs. It looks like what you're trying to do could be accomplished within an ```alterState(state => {
  // anything in javascript
  return state;
})
```
block.
