### ISSUE TITLE
Message view - redirects to a different message after "saving" message edits

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/docs#103]
When a user "saves" message edits, they are redirected to a previously viewed message, rather than the one that they _just_ edited. Steps to replicate: 

1. Select a message ("message # 1") via project inbox 
2. Click pencil to edit message body (form view)
3. Click "Save" button (don't need to actually make changes to replicate)
4. Then navigate to another message ("message # 2")
5. Repeat steps 2-3
6. After clicking "save", user will be redirected to message # 1 view, even though they just edited message # 2 (this happens even when these messages are not sequential in the inbox)

I was able to replicate with MF examples: 

1. I edited/ saved this message: https://www.openfn.org/projects/419/messages/3671322/
2. Navigated back to inbox to identify a new message
3. Edited/saved this message: https://www.openfn.org/projects/419/messages/3671391/
4. After clicking save, it redirected me back to message #3671322 instead of the #3671391 message I just edited

Not sure if helpful, but here is a screenshot of console log message visible when I "inspect" page on step #4: https://drive.google.com/file/d/1SLlSg0tfqjmFmFGVpLnqb9NiqXhx_0mj/view?usp=sharing

**Comment by aleksa-krolls** [comment]
FYI this was reported by Miracle Feet on Friday. It's been confusing to her has she's going through and editing some message bodies for messages with failed runs.

**Comment by taylordowns2000** [comment]
Issue fixed. Thank you!
