### ISSUE TITLE
Unable to copy Inbox URL (Firefox)

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/docs#104]
When accessing the OpenFn project dashboard via Firefox browser, the click to "copy inbox URL" feature does not work. Users are able to click, but the link is not successfully copied to users' clipboard. 

Users are on the latest version of Firefox (63.0.3). "Click to copy" feature works fine on Chrome and Safari browsers. 

Screenshots attached if this helps. 

<img width="1280" alt="screen shot 2018-12-06 at 9 26 23 am" src="https://user-images.githubusercontent.com/16758106/49568331-65225100-f939-11e8-8627-6a980b61ce78.png">
<img width="1280" alt="screen shot 2018-12-06 at 9 26 15 am" src="https://user-images.githubusercontent.com/16758106/49568332-65bae780-f939-11e8-9e9c-9629cfc36c81.png">
<img width="1280" alt="screen shot 2018-12-06 at 9 26 12 am" src="https://user-images.githubusercontent.com/16758106/49568333-65bae780-f939-11e8-9494-600f97161311.png">
<img width="1280" alt="screen shot 2018-12-06 at 9 26 04 am" src="https://user-images.githubusercontent.com/16758106/49568334-65bae780-f939-11e8-9e0c-2f8185e8a5d2.png">

**Comment by taylordowns2000** [comment]
Delivered in `v1.22.1`
