### ISSUE TITLE
OpenFn menu bar - Add names of menu items when user hovers over icons

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/docs#105]
When a user views the menu/navigation bar, it would be helpful if the name of the menu item (Jobs/ Credentials/ etc) appeared when a user hovers over an icon. For new users, the icons are not self-explanatory and I see users stumbling around when first trying to access the platform.

**Comment by taylordowns2000** [comment]
Hover now opens menu, revealing names of menu Items.
