### ISSUE TITLE
Not recieveing Support email  for verification Email Address for new openFN account

### ISSUE THREAD

**Issue by ShraddhaNadgauda** [OpenFn/docs#107]
Hi ,
I have created a new OpenFN account but did not receive any support email for verification. Is there any way I can resend the verification email?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Can you please take a look?

**Comment by taylordowns2000** [comment]
Hi @ShraddhaNadgauda , sorry about this. From our side it looks like your mail server accepted the email and responded with a `250 OK`. (See image below.) Can you check to make sure it didn't end up in a spam folder?
![email](https://user-images.githubusercontent.com/8732845/49925673-84792b00-feb1-11e8-9576-56c0701822de.png)
If you can't find it there, please let us know. Email admin@openfn.org and we'll get you sorted out with an email verification token, then try to troubleshoot this issue.

Best,
Taylor

**Comment by taylordowns2000** [comment]
Sorry, clicked the wrong button! I'm re-opening until you confirm that this is solved.

**Comment by ShraddhaNadgauda** [comment]
@taylordowns2000: I checked My inbox, but couldn't find any mail. Is there any way I can resend the verification email

**Comment by ShraddhaNadgauda** [comment]
@taylordowns2000 : I got the verification email but on clicking the confirm Email address I am getting this 
![openfn verification](https://user-images.githubusercontent.com/36183896/49985098-c200b580-ff90-11e8-940f-c0d21d90a8e3.png)

**Comment by taylordowns2000** [comment]
Hey @ShraddhaNadgauda , glad you got the email. To confirm, please write an email _from the address which you used to register an account on OpenFn_ to "admin@openfn.org" and we'll be able to verify your email address.

**Comment by taylordowns2000** [comment]
Strange—there's no record of an email from you in that inbox! Would you mind forwarding that message to taylor@openfn.org ?
