### ISSUE TITLE
New help button blocks last page button

### ISSUE THREAD

**Issue by sidwiesner** [OpenFn/docs#108]
<img width="457" alt="screen shot 2019-02-08 at 2 47 45 pm" src="https://user-images.githubusercontent.com/713070/52502330-852bf600-2bb0-11e9-82ef-df15cee98925.png">

The new help button is nice, but it blocks the "Last page" button for me when looking at run history and trying to scroll through results.

**Comment by taylordowns2000** [comment]
Thanks, @sidwiesner , this has been fixed.
