### ISSUE TITLE
Feature request: add status filter to Bulk Retry

### ISSUE THREAD

**Issue by sidwiesner** [OpenFn/docs#109]
If you added a status filter for "Any", "Success", and "Failure" on the Bulk Retry filter, I think that covers our majority of our use cases where we would either reprocess them individually (tediously) or ask support for help to do a custom run. It would be nice to be self-sufficient here.

Note I think this solves the intent behind #87 too.

**Comment by taylordowns2000** [comment]
Delivered in `v1.22.0`. (Also think we've got #87 covered now.) Thank you for the suggestions!

**Comment by sidwiesner** [comment]
Awesome - thanks!
