### ISSUE TITLE
Lost password needs better docs

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#131]
In lieu of a better reset flow, there should be keystroke by keystroke (or click by click) instructions for this one.... lots of people have trouble with it.

And please extend the GIF to show what you're actually doing! So... go to your email. Copy it. How do you copy it? Paste it? How? Then what do you click, etc.

**Comment by jedbgold** [comment]
ok sounds good. will do

**Comment by taylordowns2000** [comment]
see pr comment. remove potentially sensitive info and we're good to go
