### ISSUE TITLE
Develop a point-and-click interface for writing jobs

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#18]
This is the first step towards an interface that will eventually pre-populate all the destination fields and possible source values.

- [x] show the expression as data in a read-only tree/form
- [ ] allow user to "add a static node" like `create()` or `upsert()` to this tree
- [ ] fetch metadata from destination objects to allow user to "add a dynamic node" or `template` which pre-populates the destination object's fields in a `create()` block
- [ ] add JSONpaths dynamically by clicking on `blanks` in the template then clicking on a value in a receipt data modal.

**Comment by stuartc** [comment]
This feels obsolete, gonna close it.
