### ISSUE TITLE
The anatomy of an integration

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#197]
Envisioned as a primarily visual page that outlines the constituent parts of every integration to equip OpenFn users with a solid grounding of what an integration really is.

**Comment by aleksa-krolls** [comment]
@aleksa-krolls to review and provide initial feedback, with aim to merge some of this to main. 
https://github.com/OpenFn/docs/pull/208/commits/1854f5bd72a1ea4ddc9f06768a5d935ee3478490
