### ISSUE TITLE
Integrating using OpenFn

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#198]
Either a subpage of the structure page or its own page subsequent to; this maps the foundational concepts above to jobs, triggers, runs, etc. We will only introduce OpenFn-specific terminology after we establish a common frame of reference. In some ways this is just an edit of the current Getting Started page.

**Comment by aleksa-krolls** [comment]
@aleksa-krolls to review and provide initial feedback, with aim to merge some of this to main. 
https://github.com/OpenFn/docs/pull/208/commits/1854f5bd72a1ea4ddc9f06768a5d935ee3478490

**Comment by willip** [comment]
@aleksa-krolls current state on this? anything needed from me?
