### ISSUE TITLE
Revise "project walk-through"

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#200]
Revise to incorporate the below app-specific tutorials in a cohesive manner

**Comment by aleksa-krolls** [comment]
Idea is to have app-specific versions of project setup for Kobo-to-Salesforce, CommCare-to-DHIS2, etc.

**Comment by ritazagoni** [comment]
New pages:
1. How to integrate CommCare with Salesforce
2. How to integrate DHIS2 and CommCare
3. How to integrate Kobo Toolbox and a custom Postgres database
