### ISSUE TITLE
Contribute to PostgreSQL docs page 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/docs#259]
Please check out the "Integration Options" and "Authentication" sections of the Postgres docs: https://github.com/OpenFn/docs/blob/db-pages/docs/apps/postgresql.md

Can you please help fill out these sections? And any other section you feel you can add to. You can check out the Salesforce docs for inspiration: https://github.com/OpenFn/docs/blob/db-pages/docs/apps/salesforce.md

**Comment by daissatou2** [comment]
hey @lakhassane how is this going?

**Comment by lakhassane** [comment]
@daissatou2 sorry for the long wait. I have added elements for authentication. I will review more to see what else I can add. let me know also if you find anything
