### ISSUE TITLE
Edit Receipt view: improve field layout and add field groupings for more user-friendly UI

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/docs#28]
Currently the field layout is nested, mirroring the pay load. Is there a way to structure the source fields in a more user-friendly layout? It would be especially helpful to group repeat blocks and related fields (e.g., the data output of one electronic signature is three fields -- url, type, filename) in a way where it's obvious that those field values belong together. Maybe even make repeat blocks into collapsible sections?

**Comment by taylordowns2000** [comment]
- [ ] group fields by key (currently, keys with objects are not displayed... only primitives show up)
- [ ] ability to collapse groups
- [ ] general UI, font size, colors, to enhance usability.
