### ISSUE TITLE
Update devtools sample job

### ISSUE THREAD

**Issue by sunny775** [OpenFn/docs#289]
The [sample job expression](https://github.com/OpenFn/devtools/blob/main/tmp.example/expression.js) and the [sample job state](https://github.com/OpenFn/devtools/blob/main/tmp.example/state.json) in the devtools repo is for `language-dhis2` adaptor whereas the [devtools doc](https://docs.openfn.org/documentation/devtools/home/) references `language-http` :
```sh
~/devtools/core/bin/core execute \
  -l ~/devtools/adaptors/language-http \
  -s ./tmp/state.json \
  -o ./tmp/output.json \
  -e ./tmp/expression.js
```
Thus, someone following the devtools docs and trying to run the above commands will get undefined functions error like below:
![Screenshot from 2022-08-18 14-33-23](https://user-images.githubusercontent.com/49409497/185508290-ceac7a16-fdd1-4bc6-95af-af74862d4b82.png)

It will be helpful to update the devtools doc to reference `language-dhis2` which is being used in sample expression and state, or changing the sample job expression and state to those of `language-http`.

**Comment by taylordowns2000** [comment]
Thanks, @sunny775 ! We're closing this as devtools is deprcated in favor of the CLI and will be tracking cleanup issues here: #324
