### ISSUE TITLE
Improve "Configuration" page for adaptors

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#325]
- [x] The "Configuration" page is built automatically from each adaptors `configuration-schema.json` file.
- [x] The configuration page on docs should look like this:
```
## Sample configuration
{
  "a": "example",
  "b": "example"
}

## Full Schema
{
  ...FULL-JSON-SCHEMA
}
```

Once this change is made, @mtuchi 's concern about the README.md files can be addressed... when they click the link to the docs page they'll see both the full schema definition _and_ an example.

**Comment by mtuchi** [comment]
@taylordowns2000 can not proceed until this PR is merged https://github.com/OpenFn/adaptors/pull/201
