### ISSUE TITLE
Functionality for creating Receipts 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/docs#33]
Interface/functionality for creating Receipts, similar to Enketo. It could be a separate service clients pay for if they want users without mobile access to be able to enter data.

**Comment by taylordowns2000** [comment]
Thanks, @aleksa-krolls , delivered in `v1.13.0`
![image](https://user-images.githubusercontent.com/8732845/54196017-1f38d400-44b8-11e9-8a90-fc242de603d2.png)

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Nice!
