### ISSUE TITLE
Build optimized docs template for Docusaurus

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#332]
Once we've got the `adaptors` -> `docs` documentation build down, we should optimize the documentation that gets written by using:

1. A guide to cherrypicking and styling docs from `jsdoc2md`: https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Cherry-picking-which-documentation-appears-in-output
2. The documentation style guide from [docs.openfn.org](https://docs.openfn.org/documentation/style-guide/) (see [source here](https://github.com/OpenFn/docs/blob/main/docs/style-guide.md).)

## Deliverables for this issue

- [x] Mark execute as private in docs
- [ ] Sort docs alphabetically
- [ ] Template the right-hand side menu of the adaptor docs, to only show the function name and not the whole signature

**Comment by mtuchi** [comment]
Top 3 implementation planning 
- [ ] Mark execute as `private` in docs 
- [ ] Sort docs alphabetically
- [ ]  Template the right-hand side menu of the adaptor docs, to only show the function name and not the whole signature
cc @taylordowns2000

**Comment by mtuchi** [comment]
Issue moved to [OpenFn/adaptors #228](https://github.com/OpenFn/adaptors/issues/228) via [**Zenhub**](https://www.zenhub.com/)
