### ISSUE TITLE
Add documentation for CLI deploy/pull commands

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#360]
@zacck , opening this issue to track your work on https://github.com/OpenFn/docs/pull/357

in `docs/portability.md`:
- [x] how the CLI is relevant to version control and deployment
- [x] how to use cli deploy
- [x] how to use cli pull
- [x] how to set up GitHub version control on Lightning
- [x] Include highlighted section that explains how to get the CLI with the --help

Delete "dummy-deploy-test" and any other public reference to a project.yaml once the new yaml sample and docs are updated. (There's actually a final ticket https://github.com/OpenFn/projects-as-code/issues/3 to ensure that all relevant documentation has been moved.)

**Comment by zacck** [comment]
@taylordowns2000  sure thing

**Comment by zacck** [comment]
Could you please explain the `--help` requirement I am a tad unclear on that

**Comment by taylordowns2000** [comment]
For that one @zacck , we want to make sure that whoever finds this documentation is also taught how to access the built in docs from the cli itself. For deploy I'm pretty sure you can access a help interface that describes various required or optional arguments and flags. Can you ensure that your docs explain how to access that help interface via the CLI itself?

**Comment by zacck** [comment]
Oh you mean invoking `--help` ok cool I'll add a statement so such effect

**Comment by zacck** [comment]
Ok that's added
