### ISSUE TITLE
CLI challenge: markdown in examples has gone funny

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/docs#361]
Looking at the CLI challenge yesterday I noticed a bunch of bad markdown in code examples:

![image](https://github.com/OpenFn/docs/assets/7052509/2e62dd20-99a7-4fa6-adc0-8f942e187c40)

**Comment by aleksa-krolls** [comment]
@mtuchi is this still an issue? If not, then please close... otherwise please fix!

**Comment by josephjclark** [comment]
@mtuchi this still seems to be an issue on docs.openfn.org

<img width="990" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad5d9d067d3a62362abaa719ff982518917e54e1/image.png" alt="image.png" />

**Comment by mtuchi** [comment]
> @mtuchi this still seems to be an issue on docs.openfn.org

@josephjclark i have pushed a fix here #38, Please review and merge
