### ISSUE TITLE
RTM wrapup (needs to be broken out to more issues)

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/docs#363]
**Stuff that needs doing that we don't have issues for:**

- Support the sanitize log flag
- Does the existing service worker even support workflows? Does it need to do anything for that?
- At the moment we use worker threads to run the jobs (with compilation in the main thread). I don't know if this is its final form. But we should be able to swap this out later.
- Caching compiled jobs

**Comment by aleksa-krolls** [comment]
@NickOpenFn I don't think this issue belongs on the /docs repo... do you agree? Can I close this?
