### ISSUE TITLE
Salesforce OAuth Set Up

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/docs#389]
### Description 

Update [Salesforce adaptor overview page ](https://github.com/OpenFn/docs/blob/main/adaptors/salesforce.md) to include instruction of how to setup Salesforce Authorization with OAuth

### Resources 
- https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/code_sample_auth_oauth.htm
- https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_oauth_and_connected_apps.htm
- https://help.salesforce.com/s/articleView?id=sf.remoteaccess_authenticate.htm&type=5

**Comment by mtuchi** [comment]
I can not test the Salesforce OAuth locally in my machine. Based on my pairing session with @elias-ba it seems like the credential is failing to be created when you have slow internet connection

**Comment by aleksa-krolls** [comment]
@mtuchi now that this feature is live, pls consider what Adaptor docs need updating to describe how to configure Oauth as an alternative to the traditional configuration schema. We'll probably want to add a section to [this Overview page](https://docs.openfn.org/adaptors/salesforce). If you draft edits, I can review and add more Salesforce context, as needed.

**Comment by aleksa-krolls** [comment]
@mtuchi [see related slack thread](https://openfn.slack.com/archives/C06HA4WF35K/p1712238031277899) for resources to help with docs here

We'll want to update the Overview page to add an Oauth-specific credential setup guide. Right now we just have guidance for regular user credentials.
https://docs.openfn.org/adaptors/salesforce#salesforce-credentials

**Comment by aleksa-krolls** [comment]
@mtuchi [see related slack thread](https://openfn.slack.com/archives/C06HA4WF35K/p1712238031277899) for resources to help with docs here

We'll want to update the Overview page to add an Oauth-specific credential setup guide. Right now we just have guidance for regular user credentials.
https://docs.openfn.org/adaptors/salesforce#salesforce-credentials
