### ISSUE TITLE
reporting on submissions

### ISSUE THREAD

**Issue by stephanielitus** [OpenFn/docs#39]
I would like to run reports on submissions, reporting on # of submissions, submission type, user, status (success/fail), date.  It would also be nice to set filters on these fields.

Thanks!

**Comment by taylordowns2000** [comment]
@stephanielitus , I think that we'll address this in two ways:

1. We're putting together a basic user dashboard that will allow for some analysis of usage, performance (are you *always* getting validation mismatches on THIS particular job, etc.) and how close you are to your monthly limits.
2. We'll release a download as CSV button for power-users that want to export their entire history log and do quick analysis in LibreOffice Calc or MS Excel or even some third party analysis program like Tableau. Thinking aloud, many of our users might like to integrate their OpenFn accounts with an analytics platform.

I'll be in touch with updates soon.

**Comment by sidwiesner** [comment]
Funny, I was just writing up an email about a similar feature idea, and then figured I check to see if anyone else has submitted something like it. My idea is related, but not exactly the same as Steph's:

As we get deeper into enrollment, I think some simple reporting would really make our management and review of failed runs much easier.

Specifically, a report that has a date range filter, and shows a list with each active trigger, count of messages, count of messages with jobs in a failed state, and count of messages with no associate runs.

Those counts could be clickable links into the messages list with the filters already applied.

This would allow us to see and make sure we’re on top of the backlog of failures, and also quickly get into the list of relevant messages to review.

**Comment by taylordowns2000** [comment]
Closing this as custom reports are now available from Metabase—reach out to your openfn contact if you need one!
Also...

We're shifting feature requests for the various products to the [forum](https://community.openfn.org/c/feature-requests/12) and will now use these docs issues for issues related to documentation only.
