### ISSUE TITLE
CLI Challenge: COVID-19 stats endpoint not responsive

### ISSUE THREAD

**Issue by hunterachieng** [OpenFn/docs#393]
The COVID-19 challenge url is down and giving a `502` error status code when hitting the endpoint.

#### Potential Solution:
- Wait out and monitor the endpoint until it comes back online.
- Find another COVID-19 endpoint that provides similar data to be used.

#### Docs page to be updated
- https://docs.openfn.org/documentation/cli#-challenge-fetch-covid-19-metadata
- https://docs.openfn.org/documentation/next/cli-challenges#-retrieve-covid-19-metadata

**Comment by aleksa-krolls** [comment]
@mtuchi any ideas here?

**Comment by mtuchi** [comment]
Thanks @hunterachieng for flagging this, The second option seems viable `Find another COVID-19 data source`. All endpoint in https://disease.sh/ Seems to produce internal server error. 

From a quick google search i found this https://covidtracking.com/data/api. @hunterachieng, Can you spend 5 minutes to test that API, See if you can get metadata 

cc @aleksa-krolls

**Comment by mtuchi** [comment]
Good news @hunterachieng , We have community contribution that address this issue, See #402 

There are just two tiny things that needs to be worked on,
- [ ] Fix broken Urls, [See the following failed checks](https://github.com/OpenFn/docs/pull/400/checks)
- [ ] Update platform CLI challenge https://docs.openfn.org/documentation/cli#-challenge-fetch-covid-19-metadata

cc @aleksa-krolls

**Comment by aleksa-krolls** [comment]
@hunterachieng @mtuchi please note [my slack comment](https://openfn.slack.com/archives/C06HA4WF35K/p1707811642208039) re: how links to other should be updated (where you should reference file paths, and not page url paths)
