### ISSUE TITLE
workflow tutorial: http to Google Sheets

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/docs#397]
## Background
We want to have a couple of basic Workflow tutorials with job code examples that new users can copy/paste into their own Project to see how OpenFn works. 

## Request
1. Build a basic workflow that gets a list of `users` using `http` Adaptor, and then syncs the data to [this Google sheet](https://docs.google.com/spreadsheets/d/1gT4cpHSDQp8A_JIX_5lqTLTwV0xBo_u8u3ZNWALmCLc/edit#gid=0)
2. Once tested and working on the `demo-project` project on app.openfn.org, update the documentation page `docs/tutorials/tutorial.md` to provide step-by-step guidance on how to configure 

For example: 
1. Create new Workflow named `Sync user list`
2. Select the `Trigger` and change the type to `Cron Trigger`. Configure the Trigger to run every day at 8:00 AM. 
4. Select the first `Step` "New job". Rename this Step as "Get users from API". 
5. Update the Adaptor to `http` because we're connecting with a generic REST API. 
6. _and so on_...

## state
- Json Placeholder: get list of users: https://jsonplaceholder.typicode.com/users
-  Google Sheets: use Google Oauth to authenicate and post all user data to **[this sheet](https://docs.google.com/spreadsheets/d/1gT4cpHSDQp8A_JIX_5lqTLTwV0xBo_u8u3ZNWALmCLc/edit#gid=0)**

**Comment by aleksa-krolls** [comment]
@mtuchi can you pls work on this today? Want to add a couple of basic examples to docs

**Comment by aleksa-krolls** [comment]
@mtuchi for any docs changes, please create a new branch off of the `version` branch. (We're making some edits to versioning there.)

**Comment by mtuchi** [comment]
@aleksa-krolls noted 👍🏽
