### ISSUE TITLE
workflow tutorial 2: kobo to dhis2 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/docs#398]
## Background
This builds off issue #397 where we want to add more examples to docs v2. 

## Request
1. Build a basic workflow that gets a list of `forms` from Kobo toolbox. I've already did the basic configuration (**[see Kobo-to-DHIS2 workflow](https://app.openfn.org/projects/57862287-23e6-4650-8d79-e1dd88b24b1c/w/d4bf1137-d899-485b-9d70-d6611d2c7d4b?s=b48f4c9c-c3d5-4809-8fc7-2d8d7e7a155e) - update this!**. 
- Pls help me update the job code that has been drafted. 
- Count the number of Kobo forms where `OPV0 dose given` is `yes`
- FYI this workflow is inspired by the [training homework](https://github.com/OpenFn/training/blob/main/examples/2.createDataValues.js#L2-L19) example - I just want to get from Kobo instead of the OFG database. You can save your new workflow code in the [training repo](https://github.com/OpenFn/training) to back up as another example.

2. Once tested and working on the `demo-project` project on app.openfn.org, create a NEW documentation page `docs/tutorials/tutorial-kobo-dhis2.md` to provide step-by-step guidance on how to configure. (Please make base your docs branch on the `version` branch.)

For example: 
1. Create new Workflow named `Sync user list`
2. Select the `Trigger` and change the type to `Cron Trigger`. Configure the Trigger to run every day at 12:00. 
4. Select the first `Step` "New job". Rename this Step as "Get forms from Kobo". 
5. Update the Adaptor to ... _and so on_

## state
- Kobo demo account (see LP `openfn demo Kobo Account`). Query data for form id `aBpweTNdaGJQFb5EBBwUeo`
- DHIS2 Play: [https://play.im.dhis2.org/dev](https://play.im.dhis2.org/dev) (UN: `admin`, PW: `district`)

See screenshot of DHIS2 page we want to update: 
<img width="1011" alt="Screenshot 2024-02-12 at 11 39 19 AM" src="https://github.com/OpenFn/docs/assets/16758106/3b4bb271-8c8d-4f03-b86e-12746eab87c6">

**Comment by aleksa-krolls** [comment]
@mtuchi this one is next after tutorial # 1

**Comment by mtuchi** [comment]
#### Implementation Notes
**Step 1: Fetch Form Submission**
1.  Fetch form submission from Kobotoolbox for  `formId:aBpweTNdaGJQFb5EBBwUeo`
2. Return submission results to the down stream step `Aggregate Data Values`  

**Aggregate Data Values**
4. Aggregate form submission with `OPV0_dose_given: yes`  ~ should be 3

**Import DHIS2 Data Values**
1. Create `dataValueSets` set in DHIS2
```
create('dataValueSets', {
  dataSet: 'BfMAe6Itzgt', //Child Health
  completeDate: sourceValue('$.today'), //TODO: return today's date in format '2023-03-10'
  period: '202402', //Feb 2024
  orgUnit: 'DiszpKrYNg8', //Ngelehun CHC
  dataValues: [
    {
      dataElement: 'pikOziyCXbM', //# of OPV doses given
      value: sourceValue('$.sumOfOpvDosesGiven'), //TODO: return SUM # of 'opv_doses_given' across ALL patients where age < 1 year
    },
  ],
});
```

**Comment by mtuchi** [comment]
@aleksa-krolls i have update the workflow in [app.openfn.org](https://app.openfn.org/projects/57862287-23e6-4650-8d79-e1dd88b24b1c/w/d4bf1137-d899-485b-9d70-d6611d2c7d4b?s=b48f4c9c-c3d5-4809-8fc7-2d8d7e7a155e) and it's working successful.  I will create the article next

**Comment by mtuchi** [comment]
@mtuchi 
I got it working by removing completeDate
```
create('dataValueSets', state => ({
  dataSet: 'BfMAe6Itzgt', // Child Health
  period: '202402', // Feb 2024
  orgUnit: 'DiszpKrYNg8', // Ngelehun CHC
  dataValues: [
    {
      categoryOptionCombo: 'Prlt0C1RF0s', //Fixed <1yr
      dataElement: 'x3Do5e7g4Qo', // OPV0 doses given dataElement ID
      value: '3', //# of OPV0 doses given
    },
  ],
}));
```
If we wanted to map the data to `Fixed >1yr` (instead of <1yr) - you could use `psbwp3CQEhs` for categoryOptionCombo instead.

**Comment by mtuchi** [comment]
@aleksa-krolls i have update the workflow as you suggested and it works as expected 
<img width="1296" alt="Screenshot 2024-02-17 at 1 09 34 PM" src="https://github.com/OpenFn/docs/assets/6592749/6fec9e4a-ab86-4520-9a7c-20ba4bccf3a3">

**Comment by aleksa-krolls** [comment]
@mtuchi this is great! I'm merging your PR... but can you please start a new PR that adds the following: 
1. Screenshots of the config (1 for each step) 
2. Video walkthrough of the configuratio
