### ISSUE TITLE
Update adaptors/intro.mdx for v2

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#403]
This needs refreshing, and there are some links referencing the legacy docs that we should point to the new v2 docs. 

Links to review on source page path = `/adaptors`:
   linking to `/documentation/faqs#can-openfn-integrate-with-my-custom-app` (resolved as: /documentation/faqs)
   linking to `/documentation/source-apps`
   linking to `/documentation/jobs/job-studio`

**Comment by mtuchi** [comment]
We don't have v2 pages for -`/documentation/legacy/faqs` and `/documentation/source-apps`

**Comment by aleksa-krolls** [comment]
@mtuchi as discussed... either find v2 pages to link to, or update the language so that we don't need links in this section.
