### ISSUE TITLE
common.each is duplicated in the docs listing

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/docs#447]
![image](https://github.com/OpenFn/docs/assets/7052509/a193a7bb-6942-4d68-b7d1-e7b767825db3)

**Comment by mtuchi** [comment]
After investigating i found that in common adaptor we have two each function one is in `common/Adaptors.js` the other one is in `common/beta.js`. When you build docs for common it will create two documentation for each function.

You can test this in common adaptors by changing the common example to 
```
* @example
 *  beta.each("$.[*]",
 *    create("SObject",
 *    field("FirstName", sourceValue("$.firstName")))
 *  )
 ```
 Then build the docs by running `pnpm build` which will create `docs/index.md`

**Comment by josephjclark** [comment]
Thank you @mtuchi 

The correct answer here is to namespace the docs properly. Rather than printing a flat list of all operations, we list Main Operations, Utils (`util.expandReferences`), Beta (`beta.each`), HTTP (`http.get`) etc. 

We need to work this out at some stage, because the flat list of exports doesn't really marry with the modern design of adaptors (consider the new common http utils). I am not sure that the namespace design in the adaptors themselves is entirely thought through or consistent.

I've raised an issue in adaptors for common specifically: https://github.com/OpenFn/adaptors/issues/550 A short-term solution may be to simply ignore the beta namespace in the docs

But docs do need to handle the wider case of namespacing.
