### ISSUE TITLE
Conditional paths & JS expressions

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/docs#451]
We need more docs on how to write JS expressions for conditional paths, how to test & troubleshoot, and more examples. 

We have very little right now: https://docs.openfn.org/documentation/build/paths#writing-javascript-expressions-for-custom-path-conditions

**Comment by josephjclark** [comment]
I've raised an issue in Lightning to document the UI https://github.com/OpenFn/lightning/issues/1903

A little docs would go a very long way here! Maybe I'll raise something quickly today
