### ISSUE TITLE
Enrich examples for Satusehat Adaptor

### ISSUE THREAD

**Issue by AishaHassen** [OpenFn/docs#509]
The current Satusehat adaptor has some examples but it would be nice to add more examples in the FHIR context.

### Tasks

1. Add an **Overview** section for it taking some excerpts from [here](https://satusehat.kemkes.go.id/platform/docs/id/playbook/introduction/)
2. Confirm that the **Configuration** section has accurate information for configuring the auth on CLI
3. Add a description on how to add authentication to the **New Credentials** section on app.openfn.org
4. For each example in **Functions,** show how they correspond to the Satusehat postman collection
5. Add examples in **Functions** on querying using `IHS`, and other FHIR resources such as `NIK`
6. Add an example in **Functions** showing a `put` and a `post` request using a FHIR resource such as an Encounter
7. Create an **Examples** section and add some code excerpts from the HIH workflow

**Comment by aleksa-krolls** [comment]
thanks @AishaHassen - will add to next week's sprint or the week after

**Comment by josephjclark** [comment]
I know Ayodele has been working on a plan for Overview pages. I don't know how advanced he is with it but please loop him in before addressing the Overview!

Regarding postman mappings to examples - this is an interesting area but I'm not sure the best way to go about it. It's been on my list since AkiraChix but I've not touched it! yet. Can we have a connect on it before taking any action here?

**Comment by josephjclark** [comment]
Thank you for your time @AishaHassen 

I think the biggest takeaway for me is that the Satusehat examples should be based on examples in in the [postman collection](https://www.postman.com/satusehat/workspace/satusehat-public/overview). I don't think we need to link to the collection directly (we could, but as you say the link might break), but it will let us use more realistic and relevant information in the examples.

I am not convinced that showing mappings to postman directly is a great educational tool, but I do agree that we should have better examples of how to build Satusehat URLs. Or, like, if I do `get('Encounter', { subject: 1})`, it maps to a url of `${baseUrl}/Encounter?subject=1`. The docs and examples don't help make that connection.

We might also explore that relationship more in the readme and/or Overview section.

@hunterachieng I think first step is to have an example which maps to [Get Encounter by Subject](https://www.postman.com/satusehat/workspace/satusehat-public/request/30206597-af451efd-0a00-428b-b7fe-a87a99baa4f5)

**Comment by AishaHassen** [comment]
Thanks for the summary @josephjclark. I'm not very adamant that we should have a Postman in our examples, but this

>  Or, like, if I do get('Encounter', { subject: 1}), it maps to a url of ${baseUrl}/Encounter?subject=1

is more than enough for me or for any new `Satusehat` Adaptor user

**Comment by hunterachieng** [comment]
@AishaHassen  and @aleksa-krolls  I have implemented the overview documentation for `satusehat`. Do you mind checking it out on this [PR](https://github.com/OpenFn/docs/pull/593)?

I am implementing the functions in the adaptor repo

**Comment by hunterachieng** [comment]
@AishaHassen  this is currently under review for both the adaptors and docs repos
