### ISSUE TITLE
Feature Request: Filter based on this receipt

### ISSUE THREAD

**Issue by JesseTwumBoafo** [OpenFn/docs#58]
When you view a receipt you can click "filter based on this receipt".

This would give you a list of possible filters from the given receipt.

**Comment by taylordowns2000** [comment]
Hey @JesseTwumBoafo , I like this idea but the number of possible filters from a given receipt would be massive. What we are working towards, which may solve this in part, is a JSON path inspector that will allow you to click on a particular part of a message in your inbox and get the exact path to be used in filters OR in job expressions.
