### ISSUE TITLE
Filter on activity status does not reflect most recent status

### ISSUE THREAD

**Issue by stephanielitus** [OpenFn/docs#59]
On the activity page, I am filtering based on a certain job and status = Failure.  However, this is listing submissions that failed initially but have since been retried successfully.  I would like the filter to only show failures that persist.

**Comment by Natalieflp** [comment]
@taylordowns2000 what's the status of this? It's nearly impossible for me to see which submissions have gone through without going one by one through the failures list and keeping track of what number submission I was on last. It's very easy to miss submissions and then it may never be reprocessed.

**Comment by taylordowns2000** [comment]
Hi guys, this is a complex one. It has to do with generating aggregate states, which _is_ actually very near on our roadmap. We did some preliminary work on this over the last two weeks, and hope to be working on it again next week. I'm sorry that I don't have better short-term news for you, but I'll definitely keep you posted and you should know that delivery of this (and much faster, easier to work with "inbox" and "activity" pages) will take place in the next few weeks.

**Comment by taylordowns2000** [comment]
@Natalieflp , @stephanielitus , this is closed with the new receipt filters implementation. If you need to see incoming messages that have unprocessed jobs or failed final job states, you can do so on the "inbox" tab.
