### ISSUE TITLE
Add ability to mark submissions as archived or ignored

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#6]
Archive automatically after 30 days?

**Comment by carlhughes** [comment]
Also ability to delete a submission entirely?

**Comment by taylordowns2000** [comment]
@carlhughes, this functionality will need to be delivered in some way,
shape, or form, but we're being intentionally slow on providing users with
the ability to delete *anything*. Many clients rely on OpenFn as an
"audit-trail". If this is a pressing issue for you, I'm happy to delete the
submissions in question, but otherwise it may be a little while before some
sort of permanent delete functionality is released.

**Comment by taylordowns2000** [comment]
We'll also include the ability to archive receipts themselves (which may be linked to many different submissions for many different jobs.)

**Comment by taylordowns2000** [comment]
Closing this as there's been no more demand and we've addressed the message/run management concerns with better filters.
