### ISSUE TITLE
Review sample code in README.md

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/docs#61]
Test all `helper functions` and `anonymous functions` against language packs and dummy receipts locally, using fn-lang, to ensure that it works properly. Make updates to README.md as necessary.

**Comment by taylordowns2000** [comment]
@J-Feldman , this looks great. Can you confirm that it's all done? (And that the code in the job writing helper modal is up-to-date?)

**Comment by J-Feldman** [comment]
Yessir :)
