### ISSUE TITLE
Allow job with no adaptor (or add a "json POST" option) and no credential for testing

### ISSUE THREAD

**Issue by acawood777** [OpenFn/docs#64]
I'd like to test that my job code is creating the expected json output before I actually push it to my target service.

I'd like to be able to point it to an test server like http://requestb.in which doesn't require credentials, and be able to see what is generated.

Currently a new job must have both an adaptor and a credential specified.

**Comment by taylordowns2000** [comment]
@acawood777 , I think I've got just the thing for you. We're about to release "language-http" which will allow you to make HTTP requests (get, post, put, delete) to endpoints of your choosing. I will let you know as soon as this goes live.

**Comment by taylordowns2000** [comment]
@acawood777 , check this out: https://github.com/OpenFn/language-http/releases/tag/v0.0.3 

So far, there are two functions: `fetch` will perform a GET and then POST. (It's a pull adaptor to bring data into OpenFn from _any restful JSON api_—I'm VERY excited about this!) `post` will simply post, if you've already got a message coming in. In my example, I dumped the whole `state` over to the new endpoint.
