### ISSUE TITLE
Errors not displaying in logs

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/docs#66]
When I open the log usually I receive text indicating the error that occurred but now it is blank, please see the attached screenshot
![openfn error](https://cloud.githubusercontent.com/assets/17291053/16938116/88ebaaa0-4d92-11e6-8131-e68375b3154f.PNG)

**Comment by stuartc** [comment]
Hi @Natalieflp, thanks for bringing this to my attention. This appears to be a bug relating to some performance improvements we recently introduced, I'm jumping on this right now.

**Comment by stuartc** [comment]
Found the issue, and updated the front end code. Thanks again @Natalieflp!
