### ISSUE TITLE
Access exceptions from create, upsert, etc

### ISSUE THREAD

**Issue by vera-wes** [OpenFn/docs#70]
It would be really great if you could use try/catch on create, upsert, combine, and so on, but it seems like there's no way to access the exception that's thrown right now for error handling in-job, and I couldn't see how you're doing it for the console logs that are showing which errors are returned.

**Comment by vera-wes** [comment]
Don't know how I missed the inclusion of Promise in the list of usable global functions before - clear how it can be used with the new language-http functionality, but is there a way to tap into Promise for error handling with language-common functions and I'm just missing it, or would you need to expose the error differently for that?

FYI the recent changes have been great!

**Comment by stuartc** [comment]
Hey @vera-wes! Sounds like you've hit on something that I've been experimenting with. I think it's a super important albeit advanced feature - it's been quite tough finding a way to sneak this in without affecting how jobs are written; still gotta keep the easy stuff easy. :D

All our "operations", create, upsert etc return functions that take state.. which in-turn return state (or a promise that will return state).

If you take a poke around language-common, more specifically [`execute`](https://github.com/OpenFn/language-common/blob/master/src/index.js#L17) you can see it just reduces over functions with state from the last one.

So in lieu of having a concrete way for you to hook into the promises returned from the Salesforce functions, you could try wrapping the call like this:

```js
each([1,2,3], (state) => {
  return create("foo", ...)(state).catch(e => ...)
})
```
Just be sure to always return state from the Promise. *You may need to wrap the operation in a new Promise - depending on how much control you need from the result*

Also [`combine`](https://github.com/OpenFn/language-common/blob/master/src/index.js#L223) could be useful to wrap multiple steps up. We introduced combine very very early on, so I'm not sure it's available on a lot of language packs.

Let me know how you get on!

**Comment by taylordowns2000** [comment]
Hey @vera-wes , how did you get on with this? Let me know if you want to chat. If I don't hear back in a couple of days I'll mark this as closed. You'll always still be able to access @stuartc 's suggestion in the "closed issues" section of the repo.

**Comment by vera-wes** [comment]
@taylordowns2000 sorry for missing this message! we haven't had the time to try this out internally yet, but I'll let you know if that changes
