### ISSUE TITLE
Failed job is red but shows "succeeded"

### ISSUE THREAD

**Issue by acawood777** [OpenFn/docs#73]
![untitled](https://cloud.githubusercontent.com/assets/13887947/19767447/2d01e302-9c53-11e6-9dd5-f1830bd907b4.png)

**Comment by taylordowns2000** [comment]
Thank you @acawood777 . Looks like a one-line fix and will be tested and deploy by tomorrow AM. To confirm, is the run showing as "failed" (with the red X) in the Activity tab?

**Comment by acawood777** [comment]
@taylordowns2000 Affirmative

**Comment by taylordowns2000** [comment]
Great. Will close when we deploy.
