### ISSUE TITLE
Improve navigation - urls for items on Inbox / Actions

### ISSUE THREAD

**Issue by acawood777** [OpenFn/docs#76]
Desired: 
If I have a list of messages in the inbox needing attention (e.g. filtered by failed jobs) I'd like to be able to keep that list open in one tab, and rapidly view the messages in new tabs. 
Functionality should be similar to the Message/Trigger/Job url-links on the /runs/ page

Currently: 
Not possible to open an inbox message in another tab - right/middle-clicking on the message in an inbox results in the page navigating to that message.

**Comment by taylordowns2000** [comment]
Thank you! Great idea. Since these are buttons for navigation within a single page React.js application (not links) I've implemented "cntrl+click" for new tabs across the app.

Hold down control while you click on a button and it should open in a new tab/window depending on your browser settings.

**Comment by acawood777** [comment]
@taylordowns2000 Perfect, makes debugging much less of a mission, thanks!
