### ISSUE TITLE
[visual bug] Footer in power editor blocks clicking on adjacent code

### ISSUE THREAD

**Issue by carl-eis** [OpenFn/docs#77]
![image](https://cloud.githubusercontent.com/assets/4728395/20516283/7ed26058-b09e-11e6-968c-cb9064487a91.png)

**Comment by taylordowns2000** [comment]
Thanks, @carl-eis . Just pushed a fix (tests running, will be in production in about 15 min) that cleans up this editor a bit—you now get a standard top menu with the project name, job name, and your action buttons.
