### ISSUE TITLE
Allow for custom descriptions for payment receipts.

### ISSUE THREAD

**Issue by kzeigler** [OpenFn/docs#78]
Now that we have a few projects with payments and more to be expected soon, it would be really helpful to add a description to the payment receipt so that we know which payment went with which project for expense reporting on our end.

**Comment by taylordowns2000** [comment]
Great idea, thanks, @kzeigler . The standard Stripe receipts didn't display the project name from OpenFn. I've replaced them with a custom receipt that provides all the same info as before, in addition to the Project name for which the payment was captured.
