### ISSUE TITLE
Feature request: Export and search runs

### ISSUE THREAD

**Issue by vera-wes** [OpenFn/docs#80]
Hey gang - one thing that would be really helpful from our/our clients' perspective to include in the roadmap to make error handling easier (other than the promise catching that we could put into jobs themselves is to make runs more searchable - i.e. if we could search for a string *across all runs* like for the word "duplicate" or "external" then we'd be able to handle errors en masse a lot easier. 

As we realize that's a bit more of a UI task than the following, we thought maybe a good intermediate solution would be to have an "export" logs feature, where we could export all the log data for a given job, so that we can then just search that text file and least fine the specific message we're interested in. Is either of these something on the horizon? @Natalieflp feel free to weigh in more here!

**Comment by taylordowns2000** [comment]
Hey @vera-wes , this is a great idea. It's going to be heavy to do text searches across all those logs, but I'm thinking about UI performance a lot right now (we're introducing a new "filter messages by matching trigger" today) and will keep this top of mind.

Maybe we could create a separate search landing page that would look through message bodies and run logs, returning matches sorted by relevance. What do you think about that?

**Comment by aleksagk** [comment]
@taylordowns2000 This would also be really helpful, but much less important if the items in #52 are addressed.

**Comment by taylordowns2000** [comment]
Sorry for the delay @vera-wes and @aleksagk , we've just released receipt body text search to the staging servers for final testing it will be live on production by tomorrow morning at the latest.
![image](https://user-images.githubusercontent.com/8732845/29684502-915cc0ce-88e8-11e7-8ae5-658965c43c7c.png)
![image](https://user-images.githubusercontent.com/8732845/29684521-a292bd44-88e8-11e7-9b60-75f716909566.png)
