### ISSUE TITLE
DIY example CLI command fails

### ISSUE THREAD

**Issue by dannyroberts** [OpenFn/docs#85]
CLI command https://openfn.github.io/docs/documentation/#diy

> ~/fn-lang$ lib/cli.js execute -l dhis2 -e tmp/expression.js -c tmp/config.json -d tmp/message.json

fails:

```
fn-lang$ lib/cli.js execute -l dhis2 -e tmp/expression.js -c tmp/config.json -d tmp/message.json
Options:
  -l, --language    resolvable language/adaptor path                  [required]
  -e, --expression  target expression to execute                      [required]
  -s, --state       Path to initial state file.                       [required]
  -o, --output      Path to write output.
  --help            Show help                                          [boolean]

Examples:
  lib/cli.js execute -l salesforce -e       Using the salesforce language pack,
  foo.js -s state.json                      execute foo.js to STDOUT

Missing required argument: state
```

I've run all the preceding commands.

**Comment by dannyroberts** [comment]
I'm going to leave comments here as I debug the command. Hopefully that's more helpful than annoying.

I figured `-d` was a typo and changed it to `-s`, which seems right since it unmasked a different error:

```
fn-lang droberts$ lib/cli.js execute -l dhis2 -e tmp/expression.js -c tmp/config.json -s tmp/message.json
{ Error: Cannot find module 'dhis2'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at getModule (/Users/droberts/dimagi/OpenFn/fn-lang/lib/utils.js:28:14)
    at Object.<anonymous> (/Users/droberts/dimagi/OpenFn/fn-lang/lib/cli.js:139:23)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12) code: 'MODULE_NOT_FOUND' }
```

**Comment by taylordowns2000** [comment]
Definitely more helpful than annoying! I'm out to lunch now but will get on this later. For starters, do you have language-dhis2 at the path you've specificied with -l ?

Also, try using -l language-dhis2.Adaptor

Sorry this stuff is out of date. More focus on the hosted solution recently but I do mean to get and keep this side up to date as well!

**Comment by taylordowns2000** [comment]
And read the documentation on github.com/openfn/fn-lang

That should be more recent.

**Comment by dannyroberts** [comment]
OK, I'm just playing around and trying to follow examples in the documentation, to get a feel for openfn. Thanks for the quick response and helpful pointers. Changing to `language-dhis2.Adaptor` definitely helped.

I also ran `npm link .` (inside fn-lang) to make `diesl` available in the command line. Noting that since it wasn't in the docs. If you confirm that's the desired way to install it (`npm install; npm link .`) then I can make a PR to update the README.md. (Node's not my most comfortable environment, so kind of using trial and error here.)

Now it's throwing a different error:

```
fn-lang$ diesl execute -l language-dhis2.Adaptor -e tmp/expression.js -c tmp/config.json -s tmp/message.json
1
Cannot read property 'username' of undefined
fn-lang$ echo $?
1
```

I imagine it has something to do with the required format of config.json changing between the version https://openfn.github.io/docs/documentation/#diy was written for and the current version, perhaps the username now being nested or something. If I'm not off the mark, do you know if the new config.json specs are written up somewhere?

If the documentation's example isn't likely to work, I don't want to bother you too much with what's just me playing around. If it's helpful from your perspective, I'm happy to keep pushing until I get this working and then update the docs.

**Comment by taylordowns2000** [comment]
Hey @dannyroberts , now sitting back down at my desk it looks like that DIY section hasn't been updated in quite some time! [The documentation for fn-lang](https://github.com/OpenFn/fn-lang), on the other hand, is up to date. Check it out over there while I fix the docs here at OpenFn/docs. (N.B., the big difference is that state is a single JSON file with `"data"` and `"configuration"` keys.)

Also, a few months ago I put together a do-it-yourself environment at: [openfn-devtools](https://github.com/OpenFn/openfn-devtools) 

The idea here is to make it really easy for people to get up and running with OpenFn locally. You can even install fn-lang using `npm install -g github:openfn/fn-lang#v0.5.6`.

For what it's worth, in my current environment I'm running deisl using: `./lib/cli.js execute -l ../language-salesforce.FakeAdaptor -e ./tmp/expression.js -s ./tmp/carl.json -o ./tmp/output.json`

Hope this helps! And I'm excited that you're playing around with the open-source stuff. I've been thinking about how to increase the utility of these tools and the engagement from the community. Would love to know what you think after you mess around a bit. Also, please look for my update to the DIY section.

Taylor
