### ISSUE TITLE
Feature requests: Non-American dates, and timestamp on jobs older than 1 week

### ISSUE THREAD

**Issue by acawood777** [OpenFn/docs#86]
2 things in the Run history view (may also be present elsewhere):

1) Dates currently display in the American format (mm-dd-yyyy), so 01/03/2017 actually means 3 Jan and not 1 March (dd-mm-yyyy). Could you add a setting for this so users can configure which format is displayed?

2) If a run is older than 1 week the hh:mm timestamp is not displayed - is there a specific reason why these are hidden or could they be added?

Screenshot:

![image](https://cloud.githubusercontent.com/assets/13887947/21810112/19e595f8-d753-11e6-9722-d3b2b0c474c2.png)

Thanks!

**Comment by taylordowns2000** [comment]
Good call, @acawood777 . I've added hh:mm, and formatted dates before the previous week in a more universal format: YYYY-MM-DD.

**Comment by acawood777** [comment]
Great, thanks! @taylordowns2000
