### ISSUE TITLE
Feature request: Batch reprocessing

### ISSUE THREAD

**Issue by vera-wes** [OpenFn/docs#87]
It would be really great if there were a checkbox to the left in Inbox that allows you to select multiple incoming messages and then bulk edit them (e.g. click "Reprocess"). This would only work if you were sure of what job you wanted to reprocess against and all the messages fit that trigger, so maybe this could be something to include only when "Filter by job" is in use. Thought this might be useful across a lot of scenarios where you've got a bunch of failures of the same type.

**Comment by taylordowns2000** [comment]
Delivered in version `1.20`, allows bulk re-processing of messages from the `Inbox View`
