### ISSUE TITLE
Previous and Next Button from filtered list

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/docs#88]
Would it be possible to have the previous and next buttons take you to the previous and next in the list that you clicked in from? For example if I filtered on a job and on status, clicking the previous and next buttons would move me along that list, and would not show runs from other jobs, or any runs with a different status.

**Comment by taylordowns2000** [comment]
This is a super interesting feature request… I'd want the user to see the current filters that are applied while they're viewing an individual receipt. I'm closing for now as we've incorporated it into the internal roadmap. Thanks for this!
