### ISSUE TITLE
Bug report: When navigating to the next page in the inbox, it appends 1 to whatever digits are present, rather than adding one to the number.

### ISSUE THREAD

**Issue by vera-wes** [OpenFn/docs#90]
If I tell the inbox page navigation I want to go to page 5, it will take me to page 5, but then if I use the "next" button rather than using the text input page navigator, it will take me to page 51 rather than page 6. It's appending 1 to whatever page number I was just on as if it's a string rather than adding one to the number.

**Comment by taylordowns2000** [comment]
Thank you Wes. Have just pushed the fix and will deploy tomorrow AM after further testing.
