### ISSUE TITLE
Bug?: ACE editor showing "Too many errors" for successful jobs

### ISSUE THREAD

**Issue by vera-wes** [OpenFn/docs#91]
On occasion, the ACE editor will show a yellow triangle "Too many errors" even for jobs that show no signs of errors otherwise (pushing data correctly to the destination regularly). Here's one example: https://www.openfn.org/projects/2d1aa741-b608-4f7c-8d16-a6fd057c97b8/jobs/386 on line 572. I originally thought I was just making a syntax error that is for some reason not interfering with the job compiling, but it has started to seem as if this error arises only when jobs reach a certain length. Any thoughts here?
![screen shot 2017-01-30 at 3 10 32 pm](https://cloud.githubusercontent.com/assets/20986758/22418262/486654b6-e6fe-11e6-8bca-ccdcbf54a1c9.png)

**Comment by taylordowns2000** [comment]
Hey Wes, thanks for pointing this out. I'll check out the issues on Ace and see if there's some reason it can't scan big jobs. More soon.

**Comment by cardalda** [comment]
Is there any update on this topic?
It also happens with much smaller files.
In this snippet; all lines above the warning are 100% correct and show no hint or warning...

![image](https://user-images.githubusercontent.com/2777067/39405076-806608ec-4b9e-11e8-8dbf-f16f161b1f49.png)

**Comment by taylordowns2000** [comment]
Thanks for flagging this, @cardalda . @santiagogak , have you noticed this? After a quick search I found lots of other issues with software that uses AceEditor (https://ace.c9.io/) related to this warning. Makes me think it's a configuration issue related to the javascript worker: https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/javascript_worker.js#L92

**Comment by tudro** [comment]
Hello, any news on this?

Here is a js that generates this error https://gist.github.com/tudro/59c318252eecb2cb6cb1387de187741f

Thank you

**Comment by taylordowns2000** [comment]
Hi @tudro , really appreciate the sample job. (And the `"use strict";` tip!) I see that there's definitely some confusion around this in Ace itself (https://github.com/ajaxorg/ace/issues/2955) and might suggest that people follow your `"use strict;"` guidance if it suits their needs for now. I'll add this to the documentation.

**Comment by X25guru** [comment]
This is still an issue in the latest release.

**Comment by taylordowns2000** [comment]
Hi @X25guru , have you tried `'use strict;' at the top of the file? We are planning an overhaul of the IDE for later this year, and we'll consider switching away from Ace editor as this seems to be a known issue. For now, I'd try that use-strict tip, or write and test your jobs offline using https://github.com/openfn/openfn-devtools, then load them into OpenFn.org later if needed.

**Comment by X25guru** [comment]
Sorry, I thought this was ACE. Nevermind.

**Comment by ByordiShilpa** [comment]
> Thanks for flagging this! @cardalda , would you be willing to share two expressions that throw this error? One short, one long, maybe on https://gist.github.com/ ? It would help us reproduce and solve the issue.
```
a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;
a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;
a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;
a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;a;
```
It counts errors in strict mode when not in strict mode.
