### ISSUE TITLE
Cannot jump to triple-digit page numbers on inbox

### ISSUE THREAD

**Issue by stephanielitus** [OpenFn/docs#94]
I noticed that I am able to input triple-digit page numbers on the Run History Page (in order to jump ahead or backwards by page #), however, only single or double digit pages on the Inbox page.

**Comment by taylordowns2000** [comment]
Hey Steph, I think this is because the system thinks you're always done with your input in less than one second. Can you try typing your 3 digit page rapidly and see if that makes a difference? We could increase the wait, but that would make navigation slightly slower. Let me know what you find!

**Comment by vera-wes** [comment]
@taylordowns2000 alternately had you thought about just putting a button rather than making the nav centered on time delay?

**Comment by taylordowns2000** [comment]
Or bind the enter key to that input? Thoughts?

**Comment by vera-wes** [comment]
Either of those sound good to me

**Comment by taylordowns2000** [comment]
Button implemented for "go to page" feature on runs/messages lists.
