### ISSUE TITLE
Project Owner cannot add User in the User Access Area

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/docs#98]
I'm logged in as the owner of a project, and cannot add a new user. When I enter a valid email address there is a no symbol over the add user button.

**Comment by taylordowns2000** [comment]
@Natalieflp , we connected offline but I wanted to also document this here: The number of collaborators that can be added for each plan on the hosted service is available at [OpenFn: Pricing](https://www.openfn.org/pricing)
