### ISSUE TITLE
Feature request: API GET functionality for status of jobs and listing messages

### ISSUE THREAD

**Issue by acawood777** [OpenFn/docs#99]
We'd love to be able to access OpenFn via an API.

We're building a dashboard webpage that keeps tabs on all of the bits of our integrated systems. We'd like to be able to list the last 10 failed OpenFn jobs here, or show a count of failed jobs in the last 24hrs/week/month.

We'd typically like to be able to access the data currently shown on the Inbox page:
![image](https://user-images.githubusercontent.com/13887947/27029894-7a397246-4f6a-11e7-8399-abbb589b94be.png)

So:
- Get a list of Inbox messages, sorted by time received. Return timestamp, id, and last action success/failure
- Filter by content
- Filter by related runs (successful, failed, no related runs)

But also, importantly:
- Filter by timestamp

Perhaps a default limit of (e.g.) 10 records returned, but with this `num_records` parameter specifiable up to some maximum that you could decide on (e.g. 100)

**Comment by taylordowns2000** [comment]
Migrated: https://community.openfn.org/t/api-get-functionality-for-status-of-jobs-and-listing-messages/116
